# Generated by Django 2.1.4 on 2018-12-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='sliderimages',
            old_name='title',
            new_name='name',
        ),
    ]
