# Generated by Django 2.1.4 on 2018-12-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181207_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, upload_to='slider_image')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SliderImages',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='body',
        ),
        migrations.AddField(
            model_name='about',
            name='slider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Slider'),
        ),
    ]
