# Generated by Django 2.1.4 on 2018-12-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(blank=True, upload_to='slider_image'),
        ),
    ]
