# Generated by Django 2.1.4 on 2018-12-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20181208_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
