# Generated by Django 2.1.4 on 2018-12-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20181210_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer',
            new_name='Footers',
        ),
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Testimonials',
        ),
    ]
