# Generated by Django 2.1.4 on 2018-12-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20181210_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footers',
            new_name='Footer',
        ),
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
